### ISSUE TITLE
`fetch_item` requests unlocked flash

### ISSUE THREAD

**Issue by ryan-summers** [tweedegolf/sequential-storage#3] opened 2023-11-10 16:07 UTC
It seems odd that we require a `NorFlash` object for a read operation instead of a read-only flash. I looked at the code, and it looks like the only case here is that we intentionally erase the flash range if we failed to deserialize a requested item (which doesn't actually seem like what we want to do?).

I propose that we relax the bounds here and make it just request a `ReadNorFlash` object, which allows us to keep flash locked when reading, which limits the potential for unintended modifications.

**Comment by diondokter** [comment] 2023-11-10 16:14
Ah yeah, that seems reasonable!

About the erase, yeah idk. At that point something pretty bad went wrong and in principle the data is not recoverable. The only thing you could do to continue is to erase the flash.

But changing it to retuning an error is good too. The users then have to do the erase themselves.

**Comment by ryan-summers** [comment] 2023-11-10 16:22
I can look at implementation next week as well - not super pressing here, just looking at integrating this into Stabilizer so we can maintain some settings, and this crossed my mind while implementing :)

**Comment by diondokter** [comment] 2023-11-10 16:24
Oh cool! 😁

**Comment by diondokter** [comment] 2023-11-13 11:17
> Is it not possible to deserialize items without knowledge of the underlying flash page structuring? It seems like that should be possible.

In theory one could create a library where that's possible yeah, but this crate is designed page-first.
There are three problems if you don't know the page size (and thus can't find the page markers).

1. Normal data can contain sections with 0xFF. The only contract is that not ALL of them may be 0xFF. So in theory you could have some data with 100 0xFF's while the amount of free space is less than that. This means you can't really determine the difference between them.
2. You don't know where the page markers are, so they would be considered to be normal data. This will break everything.
3. We don't know the write word size. So we don't know where to round up to in some cases.

Even if we could maybe fix 1, 2 and 3 are real blockers.

The only option I really see is this:

```rust
fn fetch_item<F: NorFlash>() -> () {
    fetch_item_read_only::<F, F::WRITE_SIZE, F::ERASE_SIZE>()
}

fn fetch_item_read_only<F: ReadNorFlash, const WORD_SIZE: usize, const ERASE_SIZE: usize>() -> () {
    // The real impl
}
```

But that'd have the cost of having to add the generics everywhere

**Comment by diondokter** [comment] 2023-11-13 12:28
It's only a small portion of this issue, but I created a new release 0.4.2 where the crate doesn't auto-erase anymore and instead returns an error.

**Comment by ryan-summers** [comment] 2023-11-13 17:18
I think a more reasonable request would be to attach the flash page size to `ReadNorFlash` objects in `embedded-storage`. I don't see why that information is only applicable to writeable flash - I'll open an issue.

**Comment by diondokter** [comment] 2024-02-11 00:46
Closing this issue for now since the issue is with `embedded-storage`. If it gets updated so that the erase and write sizes are known in the norflash trait, then the issue can be reopened and I'll update the crate.

**Closed by diondokter** 2024-02-11 00:46 UTC
